name: RSpec
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  spec:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: ['3.1.2', '2.7.6', '2.3.8']
    steps:
      - uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run rspec
        run: bundle exec rspec
